### ISSUE TITLE
Hopper

### ISSUE THREAD

**Issue by mazes-80** [HybridDog/connected_chests#15]
If I try to launch a world using connected_chests and [hopper](https://codeberg.org/tenplus1/hopper)

`2024-08-25 02:05:02: ERROR[Main]: ModError: Failed to load and run script from .minetest/mods/connected_chests/init.lua:`
`2024-08-25 02:05:02: ERROR[Main]: .minetest/mods/connected_chests/init.lua:714: attempt to call method 'set_extra_container_info' (a nil value)`
`2024-08-25 02:05:02: ERROR[Main]: stack traceback:`                                                                                                                
`2024-08-25 02:05:02: ERROR[Main]:       .minetest/mods/connected_chests/init.lua:714: in main chunk`

`set_extra_container_info` seems to be present only in [facedeer hopper](https://github.com/minetest-mods/hopper)

**Comment by HybridDog** [comment]
Thanks for reporting this. 
I have changed the hopper compatibility code so that it is only executed if the set_extra_container_info function is defined, so it should no longer crash.
With TenPlus1's current version, hopper nodes do not work together with connected chests, so it behaves like in release v1.0.0.

**Comment by mazes-80** [comment]
Quite fun, I receive commit notification next morning while I was tweaking with exact same modifications :)

Extra work I could avoid :(
