### ISSUE TITLE
change shift/click

### ISSUE THREAD

**Issue by TumeniNodes** [HybridDog/connected_chests#5]
Is it possible to change from using left shift, to right shift key?

Only due to left shit reserved for down/sneak.
Just a proposal, not a huge deal

**Comment by HybridDog** [comment]
Unfortunately (server-side) mods can only test a few keys:
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3658

**Comment by TumeniNodes** [comment]
ahhh. it is not a huge deal anyway.
the only reason I even mentioned it is, when in fly mode, when you hit shift from the ground, it makes that irritating sound.
Ima close this silliness then, heh.

Are you interested in a double version of the open chest model, to add to this?
I will close this issue after you answer, and depending on your answer I will go from there

**Comment by HybridDog** [comment]
> Are you interested in a double version of the open chest model, to add to this?

I personally don't like the opening chest animation from minetest_game because you need to wait a bit until you can access the inventory (because I don't like waiting). 
However, it has an impact on gameplay and connected_chests should resemble default chests, so I am interested in the opening animation for double chests.
Also, lid opening is on the TODO list (end of the page https://github.com/HybridDog/connected_chests).

**Comment by TumeniNodes** [comment]
ok, I will work on it over the next few days then submit it
