### ISSUE TITLE
Problème de compatibilité avec pipeworks

### ISSUE THREAD

**Issue by papou30** [HybridDog/connected_chests#8]
Good evening, we noticed that big chests when they have a pipeworks pipe on the top became transparent when opening or closing them?

![screenshot_20181103_181033](https://user-images.githubusercontent.com/30324453/47955214-b505a500-df94-11e8-9847-8c2c869b8906.png)

![screenshot_20181103_181042](https://user-images.githubusercontent.com/30324453/47955217-c2229400-df94-11e8-938c-02da18c3ea3d.png)

Cordially.

**Comment by HybridDog** [comment]
![chest_halfopen](https://user-images.githubusercontent.com/3192173/47956498-9360e980-dfa5-11e8-925f-5a1b017c4292.jpg)
Opening only the left half of a chest should not be possible of course…
Thanks for reporting this problem.
It should be fixed in the newest version. https://github.com/HybridDog/connected_chests/commit/6a9f308529482ad34f8f8ae1374bea5a4d23354c
